# Install passenger
- name: Add key for passenger
  apt_key:
    url: http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xAC40B2F7
    state: present
- name: Apt add passenger to list
  apt_repository:
    repo: 'deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ansible_distribution_release}} main'
    state: present
    update_cache: yes
- name: Install Nginx dependance
  apt:
    name: "{{item}}={{nginx_version}}"
    state: present
    force: yes
  with_items:
    - nginx-common
    - nginx-extras
  notify: reload_nginx
- name: Install passenger
  apt:
    name: "passenger={{passenger_version}}"
    state: installed
    force: yes
  notify: reload_nginx

# Update conf
- name: Copy default conf
  copy:
    src: "files/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    mode: 0644
  notify: reload_nginx
- name: Copy logrotate conf
  copy:
    src: "files/logrotate"
    dest: "/etc/logrotate.d/nginx"
    mode: 0644

- name: Create passenger file
  copy:
    content: |
      passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;
      passenger_ruby /usr/local/rvm/gems/{{ruby_version}}/wrappers/ruby;
      passenger_show_version_in_header off;
      # Max number of Rails app instances (default 6)
      passenger_max_pool_size          40;
      # Max number of Rails instances per app
      passenger_max_instances_per_app  35;
      # Idle time before killing the Rails process
      passenger_pool_idle_time         300;
      # Number of requests after which the Rails process is restarted
      passenger_max_requests           3000;
      # Deactivate verbose boot error page
      passenger_friendly_error_pages   off;
      # Disallow turbocache for the moment
      passenger_turbocaching off;
    dest: "/etc/nginx/conf.d/passenger.conf"
    mode: 0644
  notify: reload_nginx

- name: Create website directory
  file:
    path: /etc/nginx/sites-enabled
    state: directory

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart_nginx

- name: Drop log directory
  file:
    path: /var/log/nginx
    state: absent
- name: Create log directory
  file:
    path: /var/log/nginx
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
