development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: getup
  pool: 5
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: getup
  pool: 5
  username: root
  password: root

production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: getup
  pool: 5
  username: root
  password: root

