development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: getup
  pool: 5
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: getup
  pool: 5
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  host: getup.cn0gi58oflts.eu-west-1.rds.amazonaws.com
  database: getup
  pool: 5
  username: getup
  password: fdlez2SxlsZLQwzl2

